set_property SRC_FILE_INFO {cfile:/home/changyisong/multi_queue_10GbE/v7_xt_conn_trd/hardware/sources/ip_catalog/pcie3_x8_ip/source/pcie3_x8_ip-PCIE_X0Y1.xdc rfile:../../sources/ip_catalog/pcie3_x8_ip/source/pcie3_x8_ip-PCIE_X0Y1.xdc id:1 order:EARLY scoped_inst:pcie_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/changyisong/multi_queue_10GbE/v7_xt_conn_trd/hardware/sources/ip_catalog/mig_axi_mm_dual/mig_axi_mm_dual/user_design/constraints/mig_axi_mm_dual.xdc rfile:../../sources/ip_catalog/mig_axi_mm_dual/mig_axi_mm_dual/user_design/constraints/mig_axi_mm_dual.xdc id:2 order:EARLY scoped_inst:mp_pfifo_inst/mig_inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/changyisong/multi_queue_10GbE/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_mac_axi_st_ip/synth/ten_gig_eth_mac_axi_st_ip.xdc rfile:../../sources/ip_catalog/ten_gig_eth_mac_axi_st_ip/synth/ten_gig_eth_mac_axi_st_ip.xdc id:3 order:EARLY scoped_inst:network_path_inst_0/xgemac_core_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/changyisong/multi_queue_10GbE/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xdc rfile:../../sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xdc id:4 order:EARLY scoped_inst:network_path_inst_0/ten_gig_eth_pcs_pma_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/changyisong/multi_queue_10GbE/v7_xt_conn_trd/hardware/sources/constraints/v7_xt_pcie.xdc rfile:../../sources/constraints/v7_xt_pcie.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:/home/changyisong/multi_queue_10GbE/v7_xt_conn_trd/hardware/sources/constraints/v7_xt_xgemac_xphy.xdc rfile:../../sources/constraints/v7_xt_xgemac_xphy.xdc id:6} [current_design]
set_property SRC_FILE_INFO {cfile:/home/changyisong/multi_queue_10GbE/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_async_fifo/axis_async_fifo/axis_async_fifo_clocks.xdc rfile:../../sources/ip_catalog/axis_async_fifo/axis_async_fifo/axis_async_fifo_clocks.xdc id:7 order:LATE scoped_inst:network_path_inst_0/rx_interface_i/axis_fifo_inst1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/changyisong/multi_queue_10GbE/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_4x1_wr_dma_s2c/axis_ic_4x1_wr_dma_s2c_clocks.xdc rfile:../../sources/ip_catalog/axis_ic_4x1_wr_dma_s2c/axis_ic_4x1_wr_dma_s2c_clocks.xdc id:8 order:LATE scoped_inst:mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/changyisong/multi_queue_10GbE/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_1x4_rd_dma_c2s/axis_ic_1x4_rd_dma_c2s_clocks.xdc rfile:../../sources/ip_catalog/axis_ic_1x4_rd_dma_c2s/axis_ic_1x4_rd_dma_c2s_clocks.xdc id:9 order:LATE scoped_inst:mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/changyisong/multi_queue_10GbE/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_mac_tx/axis_ic_mac_tx_clocks.xdc rfile:../../sources/ip_catalog/axis_ic_mac_tx/axis_ic_mac_tx_clocks.xdc id:10 order:LATE scoped_inst:mp_pfifo_inst/axis_ic_mac_tx_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/changyisong/multi_queue_10GbE/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_mac_rx/axis_ic_mac_rx_clocks.xdc rfile:../../sources/ip_catalog/axis_ic_mac_rx/axis_ic_mac_rx_clocks.xdc id:11 order:LATE scoped_inst:mp_pfifo_inst/axis_ic_mac_rx_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/changyisong/multi_queue_10GbE/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_mac_axi_st_ip/synth/ten_gig_eth_mac_axi_st_ip_clocks.xdc rfile:../../sources/ip_catalog/ten_gig_eth_mac_axi_st_ip/synth/ten_gig_eth_mac_axi_st_ip_clocks.xdc id:12 order:LATE scoped_inst:network_path_inst_0/xgemac_core_inst/inst} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y23 [get_cells {gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y22 [get_cells {gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y21 [get_cells {gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y20 [get_cells {gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[3].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y19 [get_cells {gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[4].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y18 [get_cells {gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[5].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y17 [get_cells {gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[6].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y16 [get_cells {gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[7].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PCIE3_X0Y1 [get_cells pcie_top_i/pcie_7vx_i/PCIE_3_0_i]
set_property src_info {type:SCOPED_XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X12Y53 [get_cells {pcie_top_i/pcie_7vx_i/pcie_bram_7vx_i/replay_buffer/U0/RAMB36E1[0].u_buffer}]
set_property src_info {type:SCOPED_XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X12Y54 [get_cells {pcie_top_i/pcie_7vx_i/pcie_bram_7vx_i/replay_buffer/U0/RAMB36E1[1].u_buffer}]
set_property src_info {type:SCOPED_XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X12Y90 [get_cells {pcie_top_i/pcie_7vx_i/pcie_bram_7vx_i/req_fifo/U0/RAMB18E1[0].u_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X12Y91 [get_cells {pcie_top_i/pcie_7vx_i/pcie_bram_7vx_i/req_fifo/U0/RAMB18E1[1].u_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X12Y92 [get_cells {pcie_top_i/pcie_7vx_i/pcie_bram_7vx_i/req_fifo/U0/RAMB18E1[2].u_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X12Y93 [get_cells {pcie_top_i/pcie_7vx_i/pcie_bram_7vx_i/req_fifo/U0/RAMB18E1[3].u_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X12Y96 [get_cells {pcie_top_i/pcie_7vx_i/pcie_bram_7vx_i/cpl_fifo/genblk1.CPL_FIFO_16KB.U0/SPEED_500MHz_OR_NO_DECODE_LOGIC.RAMB18E1[0].u_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X12Y97 [get_cells {pcie_top_i/pcie_7vx_i/pcie_bram_7vx_i/cpl_fifo/genblk1.CPL_FIFO_16KB.U0/SPEED_500MHz_OR_NO_DECODE_LOGIC.RAMB18E1[1].u_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X12Y98 [get_cells {pcie_top_i/pcie_7vx_i/pcie_bram_7vx_i/cpl_fifo/genblk1.CPL_FIFO_16KB.U0/SPEED_500MHz_OR_NO_DECODE_LOGIC.RAMB18E1[2].u_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X12Y99 [get_cells {pcie_top_i/pcie_7vx_i/pcie_bram_7vx_i/cpl_fifo/genblk1.CPL_FIFO_16KB.U0/SPEED_500MHz_OR_NO_DECODE_LOGIC.RAMB18E1[3].u_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X12Y100 [get_cells {pcie_top_i/pcie_7vx_i/pcie_bram_7vx_i/cpl_fifo/genblk1.CPL_FIFO_16KB.U0/SPEED_500MHz_OR_NO_DECODE_LOGIC.RAMB18E1[4].u_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X12Y101 [get_cells {pcie_top_i/pcie_7vx_i/pcie_bram_7vx_i/cpl_fifo/genblk1.CPL_FIFO_16KB.U0/SPEED_500MHz_OR_NO_DECODE_LOGIC.RAMB18E1[5].u_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X12Y102 [get_cells {pcie_top_i/pcie_7vx_i/pcie_bram_7vx_i/cpl_fifo/genblk1.CPL_FIFO_16KB.U0/SPEED_500MHz_OR_NO_DECODE_LOGIC.RAMB18E1[6].u_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X12Y103 [get_cells {pcie_top_i/pcie_7vx_i/pcie_bram_7vx_i/cpl_fifo/genblk1.CPL_FIFO_16KB.U0/SPEED_500MHz_OR_NO_DECODE_LOGIC.RAMB18E1[7].u_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:733 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y31 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:734 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y30 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:735 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y29 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:736 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y28 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:737 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y35 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:738 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y34 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:739 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y33 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:740 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y39 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:741 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y38 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:742 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y37 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:743 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y36 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:745 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y31 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:746 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y30 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:747 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y29 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:748 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y28 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:752 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y39 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:753 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y38 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:754 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y37 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:755 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y36 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:759 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y31 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:760 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y30 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:761 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y29 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:762 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y28 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:763 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y35 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:764 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y34 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:765 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y33 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:766 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y39 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:767 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y38 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:768 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y37 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:769 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y36 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:771 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y31 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:772 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y30 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:773 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y29 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:774 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y28 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:775 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y39 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:776 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y38 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:777 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y37 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:778 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y36 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:780 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y7 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:2 line:781 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y8 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:2 line:782 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y9 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:2 line:784 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y7 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:2 line:785 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y8 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:2 line:786 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y9 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:2 line:788 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y393 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:789 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y381 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:790 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y369 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:791 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y357 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:792 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y493 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:793 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y481 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:794 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y469 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:795 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y457 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:797 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y8 [get_cells -hier -filter {NAME =~ */c0_u_ddr3_infrastructure/plle2_i}]
set_property src_info {type:SCOPED_XDC file:2 line:798 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y8 [get_cells -hier -filter {NAME =~ */c0_u_ddr3_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:SCOPED_XDC file:2 line:822 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_property src_info {type:SCOPED_XDC file:2 line:823 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
set_property src_info {type:SCOPED_XDC file:2 line:1539 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:1540 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:1541 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:1542 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:1543 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y11 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:1544 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y10 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:1545 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y9 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:1546 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y15 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:1547 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y14 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:1548 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y13 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:1549 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y12 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:2 line:1551 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:1552 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:1553 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:1554 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:1558 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y15 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:1559 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y14 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:1560 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y13 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:1561 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y12 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:2 line:1565 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1566 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1567 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1568 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1569 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y11 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1570 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y10 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1571 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y9 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1572 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y15 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1573 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y14 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1574 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y13 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1575 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y12 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1577 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1578 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1579 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1580 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1581 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y15 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1582 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y14 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1583 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y13 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1584 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y12 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1586 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y1 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:2 line:1587 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y2 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:2 line:1588 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y3 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:2 line:1590 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y1 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:2 line:1591 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y2 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:2 line:1592 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y3 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:2 line:1594 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y93 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:1595 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y81 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:1596 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y69 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:1597 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y57 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:1598 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y193 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:1599 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y181 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:1600 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y169 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:1601 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y157 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:2 line:1603 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y2 [get_cells -hier -filter {NAME =~ */c1_u_ddr3_infrastructure/plle2_i}]
set_property src_info {type:SCOPED_XDC file:2 line:1604 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y2 [get_cells -hier -filter {NAME =~ */c1_u_ddr3_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:SCOPED_XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins -filter {NAME =~ */PRE} -of_objects [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_SYNC_MGMT_RESET.G_STATS.sync_mgmt_reset_tx_i/*]]
set_property src_info {type:SCOPED_XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins -filter {NAME =~ */PRE} -of_objects [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_SYNC_MGMT_RESET.G_STATS.sync_mgmt_reset_rx_i/*]]
set_property src_info {type:SCOPED_XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins -filter {NAME =~ */PRE} -of_objects [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_SYNC_MGMT_RESET.sync_mgmt_reset_i/*]]
set_property src_info {type:SCOPED_XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins -filter {NAME =~ */PRE} -of_objects [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/sync_tx_reset_i/*]]
set_property src_info {type:SCOPED_XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins -filter {NAME =~ */PRE} -of_objects [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/sync_rx_reset_i/*]]
set_property src_info {type:SCOPED_XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/rsgen/detect_link_fail/local_failure_reg] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/rsgen/sync_lf_i/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/rsgen/detect_link_fail/remote_failure_reg] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/rsgen/sync_rf_i/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/rxgen/rx_pause_control_i/good_frame_to_tx_reg] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/txgen/tx_pause_control_i/sync_i/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/rxgen/rx_pause_control_i/pause_value_to_tx_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/rxgen/rx_pause_control_i/pause_req_to_tx_reg]
set_property src_info {type:SCOPED_XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/txgen/config_sync_i/*/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/rxgen/config_sync_i/*/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/txgen/config_sync_i/tx_mtu_size_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/rxgen/config_sync_i/rx_mtu_size_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/rxgen/config_sync_i/rx_pause_ad_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/conf/rx0_out_reg[*]] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/txgen/txframer/pause_source_held_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/conf/pause_addr_hi_out_reg[*]] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/txgen/txframer/pause_source_held_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/conf/*/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/conf/*/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/rsgen/rs_disable_sync/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/conf/*/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/conf/*/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/request_tx_int_reg] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/sync_req_tx_i/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/request_rx_int_reg] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/sync_req_rx_i/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/complete_int_reg] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/sync_complete_tx_i/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/complete_int_reg] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/sync_complete_rx_i/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/ack_rx_reg] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/sync_ack_rx_i/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/ack_tx_reg] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/sync_ack_tx_i/d_1_reg]
set_property src_info {type:SCOPED_XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_small_reclock/wr_addrgray_reg[*]] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_small_reclock/wag_readsync_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_small_reclock/rd_addrgray_reg[*]] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_small_reclock/rag_writesync_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_frag_reclock/wr_addrgray_reg[*]] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_frag_reclock/wag_readsync_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_frag_reclock/rd_addrgray_reg[*]] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_frag_reclock/rag_writesync_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_byte_reclock/wr_addrgray_reg[*]] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_byte_reclock/wag_readsync_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_byte_reclock/rd_addrgray_reg[*]] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_byte_reclock/rag_writesync_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_small_reclock/rd_data_int_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_frag_reclock/rd_data_int_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/stat_add/rx_byte_reclock/rd_data_int_reg[*]]
set_property src_info {type:SCOPED_XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/rx_clk_quarter_small_reg/Q]]]] -to [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/rx_clk_quarter_small_reg/Q]]]] -setup 2
set_property src_info {type:SCOPED_XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/rx_clk_quarter_small_reg/Q]]]] -to [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/rx_clk_quarter_small_reg/Q]]]] -hold 1
set_property src_info {type:SCOPED_XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/rx_we_reg_reg/Q]]]] -to [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/rx_clk_quarter_small_reg/Q]]]] -setup 2
set_property src_info {type:SCOPED_XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/rx_we_reg_reg/Q]]]] -to [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/rx_clk_quarter_small_reg/Q]]]] -hold 1
set_property src_info {type:SCOPED_XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins {ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/rx_carry_reset_reg_reg[*]/Q}]]]] -to [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/rx_clk_quarter_small_reg/Q]]]] -setup 2
set_property src_info {type:SCOPED_XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins {ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/rx_carry_reset_reg_reg[*]/Q}]]]] -to [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/rx_clk_quarter_small_reg/Q]]]] -hold 1
set_property src_info {type:SCOPED_XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/tx_clk_quarter_small_reg/Q]]]] -to [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/tx_clk_quarter_small_reg/Q]]]] -setup 2
set_property src_info {type:SCOPED_XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/tx_clk_quarter_small_reg/Q]]]] -to [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/tx_clk_quarter_small_reg/Q]]]] -hold 1
set_property src_info {type:SCOPED_XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/tx_we_reg_reg/Q]]]] -to [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/tx_clk_quarter_small_reg/Q]]]] -setup 2
set_property src_info {type:SCOPED_XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/tx_we_reg_reg/Q]]]] -to [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/tx_clk_quarter_small_reg/Q]]]] -hold 1
set_property src_info {type:SCOPED_XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins {ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/tx_carry_reset_reg_reg[*]/Q}]]]] -to [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/tx_clk_quarter_small_reg/Q]]]] -setup 2
set_property src_info {type:SCOPED_XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins {ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/tx_carry_reset_reg_reg[*]/Q}]]]] -to [get_cells -filter is_sequential -of [get_pins -leaf -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/tx_clk_quarter_small_reg/Q]]]] -hold 1
set_property src_info {type:SCOPED_XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.address_reg_reg[*]] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/tx_hs_reg]
set_property src_info {type:SCOPED_XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.address_reg_reg[*]] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/address_tx_reg* -filter {is_sequential}]
set_property src_info {type:SCOPED_XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.address_reg_reg[*]] -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/address_rx_reg* -filter {is_sequential}]
set_property src_info {type:SCOPED_XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -of [get_pins -leaf -filter is_enable -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/mdio_master_i/mdc_ce_reg/Q]]]] -to [get_cells -of [get_pins -leaf -filter is_enable -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/mdio_master_i/mdc_ce_reg/Q]]]] -setup 26
set_property src_info {type:SCOPED_XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -of [get_pins -leaf -filter is_enable -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/mdio_master_i/mdc_ce_reg/Q]]]] -to [get_cells -of [get_pins -leaf -filter is_enable -of [get_nets -of_objects [get_pins ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/mdio_master_i/mdc_ce_reg/Q]]]] -hold 25
set_property src_info {type:SCOPED_XDC file:3 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/mdio_master_i/mdio_in_reg_reg]
set_property src_info {type:SCOPED_XDC file:4 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *rd_truegray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *rag_writesync0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 6.400
set_property src_info {type:SCOPED_XDC file:4 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *wr_gray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *wr_gray_rdclk0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 6.400
set_property src_info {type:SCOPED_XDC file:4 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *rd_lastgray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *rd_lastgray_wrclk0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 6.400
set_property src_info {type:XDC file:5 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y11 [get_cells refclk_ibuf]
set_property src_info {type:XDC file:6 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y12 [get_cells network_path_inst_0/ten_gig_eth_pcs_pma_inst/inst/ten_gig_eth_pcs_pma_block_i/gt0_gtwizard_10gbaser_multi_gt_i/gt0_gtwizard_gth_10gbaser_i/gthe2_i]
set_property src_info {type:SCOPED_XDC file:7 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins network_path_inst_0/rx_interface_i/axis_fifo_inst1/U0/m_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins network_path_inst_0/rx_interface_i/axis_fifo_inst1/U0/s_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/S00_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/S00_AXIS_ACLK]]]
set_property src_info {type:SCOPED_XDC file:8 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/S00_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/ACLK]]]
set_property src_info {type:SCOPED_XDC file:8 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/S01_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/S01_AXIS_ACLK]]]
set_property src_info {type:SCOPED_XDC file:8 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/S01_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/ACLK]]]
set_property src_info {type:SCOPED_XDC file:8 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/S02_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/S02_AXIS_ACLK]]]
set_property src_info {type:SCOPED_XDC file:8 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/S02_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/ACLK]]]
set_property src_info {type:SCOPED_XDC file:8 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/S03_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/S03_AXIS_ACLK]]]
set_property src_info {type:SCOPED_XDC file:8 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/S03_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_4x1_wr_dma_s2c_inst/inst/ACLK]]]
set_property src_info {type:SCOPED_XDC file:9 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/M00_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/M00_AXIS_ACLK]]]
set_property src_info {type:SCOPED_XDC file:9 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/M00_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/ACLK]]]
set_property src_info {type:SCOPED_XDC file:9 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/M01_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/M01_AXIS_ACLK]]]
set_property src_info {type:SCOPED_XDC file:9 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/M01_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/ACLK]]]
set_property src_info {type:SCOPED_XDC file:9 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/M02_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/M02_AXIS_ACLK]]]
set_property src_info {type:SCOPED_XDC file:9 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/M02_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/ACLK]]]
set_property src_info {type:SCOPED_XDC file:9 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/M03_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/M03_AXIS_ACLK]]]
set_property src_info {type:SCOPED_XDC file:9 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/M03_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_1x4_rd_dma_c2s_inst/inst/ACLK]]]
set_property src_info {type:SCOPED_XDC file:10 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_mac_tx_inst/inst/M00_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_mac_tx_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_mac_tx_inst/inst/M00_AXIS_ACLK]]]
set_property src_info {type:SCOPED_XDC file:10 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_mac_tx_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_mac_tx_inst/inst/M00_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_mac_tx_inst/inst/ACLK]]]
set_property src_info {type:SCOPED_XDC file:11 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_mac_rx_inst/inst/S00_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_mac_rx_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_mac_rx_inst/inst/S00_AXIS_ACLK]]]
set_property src_info {type:SCOPED_XDC file:11 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_mac_rx_inst/inst/ACLK]]] {REF_NAME !~ RAMB*}] -to [filter [all_registers -clock [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_mac_rx_inst/inst/S00_AXIS_ACLK]]] {REF_NAME !~ RAMB*}] -datapath_only [get_property PERIOD [get_clocks -of_objects [get_pins mp_pfifo_inst/axis_ic_mac_rx_inst/inst/ACLK]]]
set_property src_info {type:SCOPED_XDC file:12 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/rx_data_reclock_reg[*]] -to [get_clocks -of_objects [get_ports s_axi_aclk]]
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells ten_gig_eth_mac_axi_st_ip_core/xgmac_inst/G_MANAGEMENT.managen/G_STATS.stat/tx_data_reclock_reg[*]] -to [get_clocks -of_objects [get_ports s_axi_aclk]]
