# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-17793-golden-OptiPlex-990/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7vx485tffg1761-2

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -define VSRC_TOP=/home/golden/study/freedom/builds/u500vc707devkit/sifive.freedom.unleashed.u500vc707devkit.U500VC707DevKitConfig.v {
      /opt/Xilinx/Vivado/2016.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/Vivado/2016.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -define VSRC_TOP=/home/golden/study/freedom/builds/u500vc707devkit/sifive.freedom.unleashed.u500vc707devkit.U500VC707DevKitConfig.v {
      /home/golden/study/freedom/fpga/u500vc707devkit/src/system.v
      /home/golden/study/freedom/fpga/u500vc707devkit/src/sdio.v
      /home/golden/study/freedom/rocket-chip/vsrc/AsyncResetReg.v
      /home/golden/study/freedom/rocket-chip/vsrc/DebugTransportModuleJtag.v
      /home/golden/study/freedom/sifive-blocks/vsrc/SRLatch.v
      /home/golden/study/freedom/sifive-blocks/vsrc/vc707reset.v
      /home/golden/study/freedom/builds/u500vc707devkit/sifive.freedom.unleashed.u500vc707devkit.U500VC707DevKitConfig.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_fsm.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_ddr_w_upsizer.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_write.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_mc_wrap_cmd.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_read.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_mc_wr_cmd_fsm.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_reg.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_mc.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_or.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_ddr_axi_upsizer.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_translator.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_mc_fifo.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_ddr_axi_register_slice.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_mc_r_channel.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_mc_b_channel.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator_sel_static.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_mc_ar_channel.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator_sel.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_mc_simple_fifo.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_and.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_reg_bank.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_top.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_ddr_command_fifo.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_mc_incr_cmd.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_arbiter.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_latch_and.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_addr_decode.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_ddr_r_upsizer.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_ddr_axic_register_slice.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_mc_aw_channel.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_ddr_a_upsizer.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_latch_or.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/axi/mig_7series_v4_0_axi_mc_w_channel.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_round_robin_arb.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_rank_cntrl.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_bank_mach.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_bank_state.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_rank_mach.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_bank_cntrl.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_bank_queue.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_bank_compare.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_rank_common.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_mc.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_arb_select.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_bank_common.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_arb_mux.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_arb_row_col.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/controller/mig_7series_v4_0_col_mach.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_oclkdelay_cal.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrlvl_off_delay.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_tempmon.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_samp.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_po_cntlr.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_if_post_fifo.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ck_addr_cmd_delay.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_byte_group_io.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrcal.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_top.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrlvl.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_poc_pd.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_prbs_gen.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_edge.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_calib_top.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_poc_cc.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_mux.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_mc_phy_wrapper.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_mc_phy.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_data.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_poc_meta.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_4lanes.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_skip_calib_tap.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_dqs_found_cal.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_poc_edge_store.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_lim.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_init.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_byte_lane.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_of_pre_fifo.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_poc_tap_base.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_dqs_found_cal_hr.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_prbs_rdlvl.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_cntlr.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_rdlvl.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/phy/mig_7series_v4_0_poc_top.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/clocking/mig_7series_v4_0_clk_ibuf.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/clocking/mig_7series_v4_0_tempmon.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/clocking/mig_7series_v4_0_iodelay_ctrl.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/clocking/mig_7series_v4_0_infrastructure.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/ui/mig_7series_v4_0_ui_rd_data.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/ui/mig_7series_v4_0_ui_cmd.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/ui/mig_7series_v4_0_ui_wr_data.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/ui/mig_7series_v4_0_ui_top.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/ip_top/mig_7series_v4_0_memc_ui_top_axi.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/ip_top/mig_7series_v4_0_mem_intfc.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/ecc/mig_7series_v4_0_ecc_gen.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/ecc/mig_7series_v4_0_ecc_buf.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/ecc/mig_7series_v4_0_ecc_dec_fix.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/ecc/mig_7series_v4_0_fi_xor.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/ecc/mig_7series_v4_0_ecc_merge_enc.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/vc707mig.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707mig/vc707mig/user_design/rtl/vc707mig_mig.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707axi_to_pcie_x1/hdl/axi_pcie_v2_8_rfs.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707axi_to_pcie_x1/hdl/axi_pcie_v2_8_3_pcie_7x_v2_0_2_pipe_clock.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707axi_to_pcie_x1/hdl/axi_pcie_v2_8_3_pcie_7x_v2_0_2_qpll_wrapper.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707axi_to_pcie_x1/hdl/axi_pcie_v2_8_3_pcie_7x_v2_0_2_gt_common.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707axi_to_pcie_x1/hdl/axi_pcie_v2_8_3_pcie_7x_v2_0_2_qpll_drp.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707axi_to_pcie_x1/hdl/axi_pcie_v2_8_3_pcie_7x_v2_0_2_gtp_cpllpd_ovrd.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707axi_to_pcie_x1/trigger.v
      /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707axi_to_pcie_x1/synth/vc707axi_to_pcie_x1.v
    }
      rt::read_vhdl -lib lib_pkg_v1_0_2 /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707axi_to_pcie_x1/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_fifo_v1_0_7 /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707axi_to_pcie_x1/hdl/lib_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_bmg_v1_0_7 /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707axi_to_pcie_x1/hdl/lib_bmg_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_pcie_v2_8_3 /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707axi_to_pcie_x1/hdl/axi_pcie_v2_8_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_3_5 /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707axi_to_pcie_x1/hdl/blk_mem_gen_v8_3_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_1_3 /home/golden/study/freedom/fpga/u500vc707devkit/obj/ip/vc707axi_to_pcie_x1/hdl/fifo_generator_v13_1_vhsyn_rfs.vhd
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2016.4/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-17793-golden-OptiPlex-990/realtime/system_synth.xdc
    rt::sdcChecksum
    set rt::top system
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {./.Xil/Vivado-17793-golden-OptiPlex-990/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-17793-golden-OptiPlex-990/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
